const CARDS=[['juice','ジュース','ジュース','🥤','のみもの'],['tea','おちゃ','おちゃ','🍵','のみもの'],['water','みず','みず','💧','のみもの'],['milk','ぎゅうにゅう','ぎゅうにゅう','🥛','のみもの'],['apple','りんご','りんご','🍎','たべもの'],['banana','バナナ','バナナ','🍌','たべもの'],['cookie','おかし','おかし','🍪','たべもの'],['rice','ごはん','ごはん','🍚','たべもの'],['music','おんがく','おんがくを したい','🎵','かつどう'],['outside','そと','そとに いきたい','🌳','かつどう'],['break','やすむ','やすみたい','🛋️','かつどう'],['toilet','トイレ','トイレに いきたい','🚻','かつどう'],['again','もう1かい','もう いっかい','🔁','ことば'],['help','てつだって','てつだって ください','🙋','ことば'],['finish','おわり','おわりに します','🏁','ことば'],['no','いや','いやです','✋','ことば'],['yes','はい','はい','⭕','ことば'],['more','もっと','もっと ください','➕','ことば']].map(x=>({id:x[0],label:x[1],speech:x[2],emoji:x[3],category:x[4],kind:'item',key:'card:'+x[0]}));
const FIXED={starter:{key:'fixed:starter',kind:'prefix',label:'わたしは',speech:'わたしは',emoji:'🙋'},please:{key:'fixed:please',kind:'ending',label:'ください',speech:'ください',emoji:'🙏'}};
const ENDINGS={please:{key:'ending:please',kind:'ending',label:'ください',speech:'ください',emoji:'🙏'},want:{key:'ending:want',kind:'ending',label:'ほしいです',speech:'ほしいです',emoji:'💭'},doit:{key:'ending:doit',kind:'ending',label:'したいです',speech:'したいです',emoji:'✨'},go:{key:'ending:go',kind:'ending',label:'いきたいです',speech:'いきたいです',emoji:'🚶'}};
const LEVELS={1:'1枚で伝える',2:'1枚＋「ください」',3:'先生を呼ぶ＋要求',4:'1枚＋文末を選ぶ',5:'「わたしは」＋1枚＋文末'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),sleep=ms=>new Promise(r=>setTimeout(r,ms));
let category=load('pecsEyeCat','のみもの'),sentence=[],dwellMs=+load('pecsEyeDwell',1200),cardSize=+load('pecsEyeSize',175),stability=load('pecsEyeStability','high'),previewMode=load('pecsEyePreview','small'),confirmMs=+load('pecsEyeConfirmMs',2000),learningLevel=+load('pecsEyeLevel',1);
let correction=load('pecsEyeCorrection',{valid:false});
let dwellTarget=null,dwellStart=0,dwellRAF=0,cameraMode=false,calibrating=false,gazeSeen=false,gazeBuffer=[],fx=null,fy=null,pendingTarget=null,pendingSince=0,lastTargetSeen=0,calCollecting=false,calRaw=[],calPairs=[];
let pendingChoice=null,confirmTimer=null,confirmRAF=0,actionCooldownUntil=0,blockedGazeEl=null,blockedLeftAt=0;
const cats=['のみもの','たべもの','かつどう','ことば'];
const CALPTS=[[50,50],[15,20],[85,20],[15,50],[85,50],[15,82],[85,82],[50,82],[50,18]],ICONS=['⭐','🎈','🐶','🍎','🚗','🐱','🌈','🎵','🌟'];
const CFG={high:{n:11,a:.14,d:22,step:78,hold:170,grace:280,pad:38,label:'高'},normal:{n:7,a:.24,d:13,step:110,hold:110,grace:190,pad:28,label:'標準'},fast:{n:5,a:.38,d:6,step:160,hold:60,grace:120,pad:18,label:'反応優先'}};
function cfg(){return CFG[stability]||CFG.high}
function itemInSentence(){return sentence.find(x=>x.kind==='item'||String(x.key||'').startsWith('card:'))}
function endingInSentence(){return sentence.find(x=>x.kind==='ending')}
function prefixInSentence(){return sentence.find(x=>x.kind==='prefix')}
function lockedKeys(){return new Set(sentence.map(x=>x.key).filter(Boolean))}
function isLocked(key){return !!key&&lockedKeys().has(key)}
function resetFilter(){gazeBuffer=[];fx=fy=null;pendingTarget=null;pendingSince=lastTargetSeen=0;clearDwell()}
function median(v){const a=[...v].sort((x,y)=>x-y),m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])/2}
function applyCorrection(x,y){if(!correction.valid)return{x,y};if(correction.type==='affine2d')return{x:correction.ax*x+correction.bx*y+correction.cx,y:correction.ay*x+correction.by*y+correction.cy};if(Number.isFinite(correction.sx))return{x:correction.sx*x+correction.bx,y:correction.sy*y+correction.by};return{x,y}}
function filterPoint(x,y){const q=applyCorrection(x,y),c=cfg();x=q.x;y=q.y;if(x<-240||y<-240||x>innerWidth+240||y>innerHeight+240)return null;gazeBuffer.push({x,y});while(gazeBuffer.length>c.n)gazeBuffer.shift();const mx=median(gazeBuffer.map(v=>v.x)),my=median(gazeBuffer.map(v=>v.y));if(fx===null){fx=mx;fy=my;return{x:fx,y:fy}}const rawDist=Math.hypot(mx-fx,my-fy),fastMove=rawDist>150,a=fastMove?Math.max(.36,c.a):c.a,maxStep=fastMove?Math.max(170,c.step):c.step;let tx=fx+a*(mx-fx),ty=fy+a*(my-fy),dx=tx-fx,dy=ty-fy,dist=Math.hypot(dx,dy);if(!fastMove&&dist<c.d)return{x:fx,y:fy};if(dist>maxStep){const k=maxStep/dist;tx=fx+dx*k;ty=fy+dy*k}fx=Math.max(0,Math.min(innerWidth,tx));fy=Math.max(0,Math.min(innerHeight,ty));return{x:fx,y:fy}}
function levelStatus(){return `レベル${learningLevel}：${LEVELS[learningLevel]}`}
function renderToolbar(){const item=!!itemInSentence(),ending=!!endingInSentence(),prefix=!!prefixInSentence();let html='';if(learningLevel>=3)html+=`<button class="tool gazeable teacher-call" data-action="callTeacher">👩‍🏫 せんせいを よぶ<div class="dwell"></div></button>`;if(learningLevel===2||learningLevel===3)html+=`<span class="fixed-chip">🙏 「ください」は固定</span>`;if(learningLevel===4){for(const [k,e] of Object.entries(ENDINGS))html+=`<button class="tool gazeable ending-tool ${ending?'locked':''}" data-ending="${k}" ${!item||ending?'disabled':''}>${e.emoji} ${e.label}<div class="dwell"></div></button>`}if(learningLevel===5){html+=`<button class="tool gazeable ${prefix?'locked':''}" data-fixed="starter" ${prefix?'disabled':''}>🙋 わたしは<div class="dwell"></div></button>`;for(const [k,e] of Object.entries(ENDINGS))html+=`<button class="tool gazeable ending-tool ${ending?'locked':''}" data-ending="${k}" ${!item||ending?'disabled':''}>${e.emoji} ${e.label}<div class="dwell"></div></button>`}html+=`<button class="tool gazeable" data-action="undo">↩ 1つもどす<div class="dwell"></div></button>`;$('#toolbar').innerHTML=html;$$('#toolbar [data-ending]').forEach(b=>b.onclick=e=>requestEnding(e.currentTarget.dataset.ending,e.currentTarget));$$('#toolbar [data-fixed]').forEach(b=>b.onclick=e=>requestFixed(e.currentTarget.dataset.fixed,e.currentTarget));$$('#toolbar [data-action]').forEach(b=>b.onclick=e=>runAction(e.currentTarget.dataset.action,e.currentTarget));bindPointer()}
function render(){document.documentElement.style.setProperty('--card',cardSize+'px');$('#levelBadge').textContent=levelStatus();const hasItem=!!itemInSentence();$('#tabs').innerHTML=cats.map(c=>`<button class="tab gazeable ${c===category?'active':''}" data-cat="${c}">${c}<div class="dwell"></div></button>`).join('');$$('.tab').forEach(b=>b.onclick=()=>{category=b.dataset.cat;save('pecsEyeCat',category);lockAction(b);render()});$('#grid').innerHTML=CARDS.filter(c=>c.category===category).map(c=>{const locked=hasItem||isLocked(c.key);return `<button class="card gazeable ${locked?'locked':''}" data-id="${c.id}" ${locked?'disabled':''}><div class="emoji">${c.emoji}</div><div class="label">${c.label}</div><div class="dwell"></div></button>`}).join('');$$('.card').forEach(b=>b.onclick=()=>requestCard(b.dataset.id,b));renderToolbar();bindPointer();renderSentence()}
function renderSentence(){const b=$('#sentence');b.innerHTML=sentence.length?sentence.map((x,i)=>`<button class="sentence-card" data-i="${i}" title="タッチで外す">${x.emoji||''} ${x.label}</button>`).join(''):'<span style="color:#98a2b3;font-size:22px;font-weight:800">カードを えらんでね</span>';$$('.sentence-card').forEach(b=>b.onclick=()=>{sentence.splice(+b.dataset.i,1);render();$('#status').textContent='ことばから外しました'})}
function requestCard(id,source){const c=CARDS.find(x=>x.id===id);if(!c||itemInSentence())return;openConfirm({...c,kind:'item'},source)}
function requestFixed(name,source){const c=FIXED[name];if(!c||isLocked(c.key))return;if(name==='starter'&&learningLevel===5&&itemInSentence()){$('#status').textContent='「わたしは」は最初に選んでね';return}openConfirm(c,source)}
function requestEnding(name,source){const c=ENDINGS[name];if(!c||endingInSentence())return;if(!itemInSentence()){$('#status').textContent='まず絵カードを選んでね';return}openConfirm(c,source)}
function openConfirm(choice,source){if(pendingChoice)return;pendingChoice={...choice};clearDwell();blockedGazeEl=source||null;$('#pending').innerHTML=`<div><div class="pemoji">${choice.emoji||'💬'}</div><div class="plabel">${choice.label}</div></div>`;$('#confirm').classList.add('on');$('#yesProgress').style.width='0%';cancelAnimationFrame(confirmRAF);if(confirmMs<=0){$('#countdown').textContent='「はい」を見て決めてね';return}$('#countdown').textContent=`${(confirmMs/1000).toFixed(1)}秒で「はい」になります`;const start=performance.now(),duration=confirmMs;const tick=()=>{if(!pendingChoice)return;const elapsed=performance.now()-start,p=Math.min(100,elapsed/duration*100);$('#yesProgress').style.width=p+'%';$('#countdown').textContent=`あと ${Math.max(0,Math.ceil((duration-elapsed)/100)/10).toFixed(1)}秒で「はい」`;if(p>=100)confirmYes();else confirmRAF=requestAnimationFrame(tick)};confirmRAF=requestAnimationFrame(tick)}
function closeConfirm(){cancelAnimationFrame(confirmRAF);confirmRAF=0;pendingChoice=null;$('#confirm').classList.remove('on');clearDwell();actionCooldownUntil=performance.now()+900;pendingTarget=null;pendingSince=0}
function confirmYes(){if(!pendingChoice)return;const c={...pendingChoice};if(c.kind==='item'){if(learningLevel===1)sentence=[c];else if(learningLevel===2||learningLevel===3)sentence=[c,{...FIXED.please,fixed:true}];else sentence.push(c)}else sentence.push(c);closeConfirm();render();$('#status').textContent=`「${c.label}」を ことばに入れました`}
function confirmNo(){if(!pendingChoice)return;const label=pendingChoice.label;closeConfirm();$('#status').textContent=`「${label}」は やめました`}
function callTeacher(source){lockAction(source);const u=new SpeechSynthesisUtterance('せんせい きてください');u.lang='ja-JP';u.rate=.82;speechSynthesis.cancel();speechSynthesis.speak(u);$('#status').textContent='先生を呼びました。先生が来たら、伝えたいものを選ぼう';actionCooldownUntil=performance.now()+2600}
function runAction(action,source){if(action==='undo'){sentence.pop();render();$('#status').textContent='1つもどしました';lockAction(source)}else if(action==='callTeacher')callTeacher(source)}
function speak(){if(!sentence.length)return;const u=new SpeechSynthesisUtterance(sentence.map(x=>x.speech||x.label).join(' '));u.lang='ja-JP';u.rate=.85;speechSynthesis.cancel();speechSynthesis.speak(u)}
function clearDwell(){if(dwellRAF)cancelAnimationFrame(dwellRAF);if(dwellTarget){dwellTarget.classList.remove('gaze');const d=dwellTarget.querySelector('.dwell');if(d)d.style.setProperty('--p','0%')}dwellTarget=null;dwellRAF=0}
function lockAction(el){blockedGazeEl=el||blockedGazeEl;blockedLeftAt=0;actionCooldownUntil=performance.now()+550;clearDwell()}
function activate(el){if(!el||el.disabled)return;if(el.dataset.id){blockedGazeEl=el;requestCard(el.dataset.id,el)}else if(el.dataset.fixed){blockedGazeEl=el;requestFixed(el.dataset.fixed,el)}else if(el.dataset.ending){blockedGazeEl=el;requestEnding(el.dataset.ending,el)}else if(el.dataset.action){blockedGazeEl=el;runAction(el.dataset.action,el)}else{lockAction(el);el.click()}}
function startDwell(el){if(!el||el.disabled||dwellTarget===el||performance.now()<actionCooldownUntil)return;if(blockedGazeEl===el)return;clearDwell();dwellTarget=el;dwellStart=performance.now();el.classList.add('gaze');const d=el.querySelector('.dwell');const tick=()=>{if(!dwellTarget)return;const p=Math.min(100,(performance.now()-dwellStart)/dwellMs*100);if(d)d.style.setProperty('--p',p+'%');if(p>=100){const t=dwellTarget;clearDwell();activate(t)}else dwellRAF=requestAnimationFrame(tick)};dwellRAF=requestAnimationFrame(tick)}
function bindPointer(){$$('.gazeable').forEach(el=>{el.onpointerenter=()=>{if(!cameraMode)startDwell(el)};el.onpointerleave=()=>{if(!cameraMode){clearDwell();if(blockedGazeEl===el)blockedGazeEl=null}}})}
function targetNear(x,y){const p=cfg().pad;let best=null,bd=Infinity;for(const el of $$('.gazeable:not(:disabled)')){if(!el.offsetParent)continue;const r=el.getBoundingClientRect();if(x>=r.left-p&&x<=r.right+p&&y>=r.top-p&&y<=r.bottom+p){const d=Math.hypot(x-(r.left+r.right)/2,y-(r.top+r.bottom)/2);if(d<bd){bd=d;best=el}}}return best}
function manageTarget(t){const now=performance.now(),c=cfg();if(performance.now()<actionCooldownUntil){clearDwell();return}if(blockedGazeEl){if(t!==blockedGazeEl){if(!blockedLeftAt)blockedLeftAt=now;if(now-blockedLeftAt>350){blockedGazeEl=null;blockedLeftAt=0}}else blockedLeftAt=0}if(t&&t!==blockedGazeEl){lastTargetSeen=now;if(pendingTarget!==t){pendingTarget=t;pendingSince=now;if(dwellTarget!==t)clearDwell()}else if(now-pendingSince>=c.hold&&dwellTarget!==t)startDwell(t)}else if(now-lastTargetSeen>c.grace){pendingTarget=null;pendingSince=0;clearDwell()}}
function handleGaze(x,y){if(!cameraMode||calibrating||!Number.isFinite(x)||!Number.isFinite(y))return;gazeSeen=true;const p=filterPoint(x,y);if(!p)return;const t=targetNear(p.x,p.y);let dx=p.x,dy=p.y;if(t&&dwellTarget===t){const r=t.getBoundingClientRect();dx=(r.left+r.right)/2;dy=(r.top+r.bottom)/2}const cur=$('#cursor');cur.style.left=dx+'px';cur.style.top=dy+'px';cur.classList.add('on');manageTarget(t)}
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.crossOrigin='anonymous';s.onload=res;s.onerror=()=>rej(new Error('視線ライブラリを読み込めません: '+src));document.head.appendChild(s)})}async function loadWebgazer(){if(window.webgazer)return;try{await loadScript('https://cdn.jsdelivr.net/npm/webgazer@3.5.3/dist/webgazer.js')}catch{await loadScript('https://webgazer.cs.brown.edu/webgazer.js')}if(!window.webgazer)throw new Error('WebGazerが見つかりません')}
function applyPreview(forceHide=false){const box=document.getElementById('webgazerVideoContainer');if(!box)return;const mode=forceHide?'hidden':previewMode;if(mode==='hidden'){box.style.display='none';try{webgazer.showVideo(false);webgazer.showFaceOverlay(false);webgazer.showFaceFeedbackBox(false)}catch{}return}try{webgazer.showVideo(true);webgazer.showFaceOverlay(true);webgazer.showFaceFeedbackBox(true);webgazer.setVideoViewerSize(mode==='small'?150:260,mode==='small'?112:195)}catch{}box.style.display='block';box.style.position='fixed';box.style.left='auto';box.style.top='auto';box.style.right='8px';box.style.bottom='8px';box.style.zIndex='9997'}
function solve3(M,v){const a=M.map((r,i)=>[...r,v[i]]);for(let i=0;i<3;i++){let p=i;for(let j=i+1;j<3;j++)if(Math.abs(a[j][i])>Math.abs(a[p][i]))p=j;if(Math.abs(a[p][i])<1e-8)return null;[a[i],a[p]]=[a[p],a[i]];const d=a[i][i];for(let k=i;k<4;k++)a[i][k]/=d;for(let j=0;j<3;j++)if(j!==i){const f=a[j][i];for(let k=i;k<4;k++)a[j][k]-=f*a[i][k]}}return[a[0][3],a[1][3],a[2][3]]}
function fitAffine(pairs){if(pairs.length<5)return null;let M=[[0,0,0],[0,0,0],[0,0,0]],vx=[0,0,0],vy=[0,0,0];for(const p of pairs){const f=[p.px,p.py,1];for(let i=0;i<3;i++){vx[i]+=f[i]*p.tx;vy[i]+=f[i]*p.ty;for(let j=0;j<3;j++)M[i][j]+=f[i]*f[j]}}const X=solve3(M,vx),Y=solve3(M,vy);if(!X||!Y)return null;const c={type:'affine2d',ax:X[0],bx:X[1],cx:X[2],ay:Y[0],by:Y[1],cy:Y[2],valid:true};const errs=pairs.map(p=>Math.hypot(c.ax*p.px+c.bx*p.py+c.cx-p.tx,c.ay*p.px+c.by*p.py+c.cy-p.ty));c.rmse=Math.sqrt(errs.reduce((a,b)=>a+b*b,0)/errs.length);return{c,errs}}
function buildPersonalCorrection(){if(calPairs.length<5){correction={valid:false};updateCorrectionText();return}let pairs=[...calPairs],fit=fitAffine(pairs);if(!fit){correction={valid:false};updateCorrectionText();return}const sorted=[...fit.errs].sort((a,b)=>a-b),med=sorted[Math.floor(sorted.length/2)],keep=pairs.filter((p,i)=>fit.errs[i]<=Math.max(100,med*2.1));if(keep.length>=6&&keep.length<pairs.length){const refit=fitAffine(keep);if(refit)fit=refit}let c=fit.c;c.ax=Math.max(.35,Math.min(2.8,c.ax));c.by=Math.max(.35,Math.min(2.8,c.by));c.bx=Math.max(-1.1,Math.min(1.1,c.bx));c.ay=Math.max(-1.1,Math.min(1.1,c.ay));c.cx=Math.max(-innerWidth*.8,Math.min(innerWidth*.8,c.cx));c.cy=Math.max(-innerHeight*.8,Math.min(innerHeight*.8,c.cy));correction=c;save('pecsEyeCorrection',correction);updateCorrectionText()}
function updateCorrectionText(){if(!correction.valid){$('#correctionText').textContent='個人補正：未設定';return}const acc=Number.isFinite(correction.rmse)?` 推定誤差${Math.round(correction.rmse)}px`:'';$('#correctionText').textContent=`個人補正：ON${acc}`}
async function runGazeGame(){calibrating=true;gazeSeen=false;calPairs=[];resetFilter();$('#cursor').classList.remove('on');$('#cal').classList.add('on');applyPreview(true);$('#error').textContent='';for(let i=0;i<CALPTS.length&&cameraMode;i++){document.querySelectorAll('.caltarget').forEach(x=>x.remove());const [xp,yp]=CALPTS[i],tx=innerWidth*xp/100,ty=innerHeight*yp/100,t=document.createElement('div');t.className='caltarget';t.style.left=xp+'%';t.style.top=yp+'%';t.innerHTML=`<span class="ring"></span><span>${ICONS[i%ICONS.length]}</span>`;$('#cal').appendChild(t);$('#instruction').textContent=`${i+1}/${CALPTS.length}　出てきたものを見つめてね`;$('#calStatus').textContent='';$('#calhint').textContent=i<3?'見つめるだけでOK！':i<6?'いいね！そのまま目で追ってね':'あと少し！下の方も見てみよう';await sleep(420);if(!cameraMode)break;t.classList.add('recording');calRaw=[];calCollecting=false;let warm=performance.now();while(cameraMode&&performance.now()-warm<240){try{webgazer.recordScreenPosition(tx,ty,'click')}catch{}await sleep(80)}calRaw=[];calCollecting=true;const started=performance.now();while(cameraMode&&performance.now()-started<680){try{webgazer.recordScreenPosition(tx,ty,'click')}catch{}await sleep(85)}calCollecting=false;if(calRaw.length>=4)calPairs.push({px:median(calRaw.map(v=>v.x)),py:median(calRaw.map(v=>v.y)),tx,ty});t.classList.remove('recording');t.classList.add('good');t.querySelector('span:last-child').textContent='✨';await sleep(150)}document.querySelectorAll('.caltarget').forEach(x=>x.remove());if(!cameraMode)return;buildPersonalCorrection();calibrating=false;resetFilter();$('#cal').classList.remove('on');applyPreview(false);$('#cursor').classList.add('on');$('#dot').className='dot on';$('#status').textContent=correction.valid?'調整完了：この人に合わせた視線補正を使っています':'調整完了：視線入力を開始しました'}
function errText(e){return `${e?.name||'Error'}: ${e?.message||String(e)}`}async function startCamera(){await stopCamera(false);cameraMode=true;calibrating=true;gazeSeen=false;resetFilter();$('#cal').classList.add('on');$('#error').textContent='';$('#instruction').textContent='カメラと視線モデルを準備しています。';$('#calStatus').textContent='準備中…';$('#dot').className='dot warn';$('#mode').textContent='操作：Webカメラ視線';try{if(!window.isSecureContext)throw new Error('HTTPSではありません');if(!navigator.mediaDevices?.getUserMedia)throw new Error('このブラウザはカメラAPIに対応していません');await loadWebgazer();if(webgazer.params)webgazer.params.faceMeshSolutionPath='https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619';try{webgazer.saveDataAcrossSessions(false);webgazer.applyKalmanFilter(true)}catch{}try{webgazer.setCameraConstraints({video:{width:{ideal:1280},height:{ideal:720},facingMode:'user'},audio:false})}catch{}webgazer.setGazeListener(d=>{if(!d)return;if(calibrating&&calCollecting&&Number.isFinite(d.x)&&Number.isFinite(d.y))calRaw.push({x:d.x,y:d.y});else handleGaze(d.x,d.y)});try{webgazer.setRegression('ridge')}catch{}await webgazer.begin(()=>{$('#calStatus').textContent='カメラを開けませんでした。'});applyPreview(true);$('#calStatus').textContent='準備完了';await sleep(350);runGazeGame()}catch(e){cameraMode=false;calibrating=false;$('#dot').className='dot';$('#mode').textContent='操作：タッチ／マウス／外部視線装置';$('#calStatus').textContent='開始できませんでした。';$('#error').textContent=errText(e)}}async function stopCamera(close=true){cameraMode=false;calibrating=false;calCollecting=false;gazeSeen=false;resetFilter();$('#cursor').classList.remove('on');$('#dot').className='dot';$('#mode').textContent='操作：タッチ／マウス／外部視線装置';try{if(window.webgazer)await webgazer.end()}catch{}if(close)$('#cal').classList.remove('on')}
$('#cameraBtn').onclick=startCamera;$('#pointerBtn').onclick=()=>stopCamera();$('#cancelCal').onclick=()=>stopCamera();$('#yesBtn').onclick=confirmYes;$('#noBtn').onclick=confirmNo;$('#speakBtn').onclick=speak;$('#clearBtn').onclick=()=>{sentence=[];render();$('#status').textContent='ことばを全部消しました'};
$('#settingsBtn').onclick=()=>{$('#dwellSelect').value=dwellMs;$('#sizeSelect').value=cardSize;$('#stabilitySelect').value=stability;$('#previewSelect').value=previewMode;$('#confirmSelect').value=String(confirmMs);$('#levelSelect').value=String(learningLevel);$('#settings').classList.add('open')};$('#closeBtn').onclick=()=>$('#settings').classList.remove('open');$('#dwellSelect').onchange=e=>{dwellMs=+e.target.value;save('pecsEyeDwell',dwellMs);$('#dwellText').textContent=(dwellMs/1000).toFixed(1)+'秒'};$('#sizeSelect').onchange=e=>{cardSize=+e.target.value;save('pecsEyeSize',cardSize);render()};$('#stabilitySelect').onchange=e=>{stability=e.target.value;save('pecsEyeStability',stability);resetFilter();$('#stabilityText').textContent=cfg().label};$('#previewSelect').onchange=e=>{previewMode=e.target.value;save('pecsEyePreview',previewMode);if(cameraMode&&!calibrating)applyPreview(false)};$('#confirmSelect').onchange=e=>{confirmMs=+e.target.value;save('pecsEyeConfirmMs',confirmMs)};$('#levelSelect').onchange=e=>{learningLevel=+e.target.value;save('pecsEyeLevel',learningLevel);sentence=[];render();$('#status').textContent=levelStatus()+' に変更しました'};$('#recalBtn').onclick=()=>{$('#settings').classList.remove('open');cameraMode?runGazeGame():startCamera()};$('#resetCorrectionBtn').onclick=()=>{correction={valid:false};localStorage.removeItem('pecsEyeCorrection');updateCorrectionText();resetFilter()};$('#stopBtn').onclick=()=>{stopCamera();$('#settings').classList.remove('open')};
$('#dwellText').textContent=(dwellMs/1000).toFixed(1)+'秒';$('#stabilityText').textContent=cfg().label;updateCorrectionText();render();